apiVersion: v1
kind: Service
metadata:
  name: webapp-websocket-service
  labels:
    app: webapp-production
    component: websocket
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/azure-load-balancer-resource-group: "webapp-prod-dev-rg"
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  ports:
  - port: 3002
    targetPort: 3002
    protocol: TCP
    name: http
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  selector:
    app: webapp-production
    component: websocket
  sessionAffinity: ClientIP  # Important for WebSocket sticky sessions

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-websocket-headless
  labels:
    app: webapp-production
    component: websocket
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 3002
    targetPort: 3002
    protocol: TCP
    name: http
  selector:
    app: webapp-production
    component: websocket
