apiVersion: v1
kind: Namespace
metadata:
  name: webapp-production
  labels:
    app: webapp-production
    environment: production
    managed-by: kustomize
  annotations:
    description: "Production web application namespace"
    contact: "devops-team"
